### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by howoow** [xtfge/vue-cesium-draw#26]
cesium版本1.96.0
cesium-draw版本3.4.5
按照readme.md的操作引入到自己的cesium文件中，报以下错误：
TypeError: Cannot read properties of undefined (reading 'prototype')
    at 5924 (cesiumdrawViewer.umd.min.js:25:1)
    at i (cesiumdrawViewer.umd.min.js:1:1)
    at 4b26 (cesiumdrawViewer.umd.min.js:25:1)
    at i (cesiumdrawViewer.umd.min.js:1:1)
    at 5128 (cesiumdrawViewer.umd.min.js:25:1)
    at i (cesiumdrawViewer.umd.min.js:1:1)
    at Object.e974 (cesiumdrawViewer.umd.min.js:40:1)
    at i (cesiumdrawViewer.umd.min.js:1:1)
    at Object.eval (cesiumdrawViewer.umd.min.js:25:1)
    at i (cesiumdrawViewer.umd.min.js:25:1)
![image](https://github.com/xtfge/cesium-draw/assets/116860649/4d2051ae-bb71-4364-bb2d-6e886b0e656c)

**Comment by howoow** [comment]
应该是该组件在Vue3项目中不兼容产生的问题😮

**Comment by xtfge** [comment]
请确定插件版本和Vue版本对应

**Comment by xtfge** [comment]
请确定插件版本和Vue版本对应
